# -*- coding: utf-8 -*-
"""Estudo_Dirigido_Antônio_Paulo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DEQQQoGPXI7knRUY8uqQCI7-D-pDmxWh

# Estudo Dirigido – Inteligência Artificial 2026.1
**Dupla:** Antônio Carlos da Silva Batista Vaz e Paulo Eduardo Vieira Souza

**Base de dados:** [Microdados Censo da Educação Superior 2020 (Kaggle)](https://www.kaggle.com/datasets/mistergomes/microdados-educacao-superior-2020)

## 1. Descrição da Base e Variáveis (Itens 1 a 4)
Neste trabalho, nosso objetivo é prever a categoria administrativa de cursos de graduação no Brasil (Pública ou Privada) utilizando um classificador Naive Bayes. Para isso, utilizamos os microdados do **Censo da Educação Superior 2020** (via INEP/Kaggle).

*   **Variável Alvo ($Y$):** `TP_REDE` (Mapeada para 0 = Pública, 1 = Privada).
*   **Características ($X$):** Escolhemos variáveis que descrevem o "tamanho" e o formato do curso:
    *   $X_1$: `QT_ING` (Quantidade de Ingressantes) - Contínua.
    *   $X_2$: `QT_MAT` (Quantidade de Matrículas) - Contínua.
    *   $X_3$: `TP_MODALIDADE_ENSINO` (0 = Presencial, 1 = EaD) - Categórica binária.

*Nota técnica:* Optamos por baixar a base diretamente via API do Kaggle no código, pois descobrimos durante o desenvolvimento que o upload manual no Colab truncava o arquivo silenciosamente, corrompendo a nossa contagem de linhas.
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy.stats import norm, expon, kstest
from scipy.integrate import quad
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report, ConfusionMatrixDisplay
import subprocess
import kagglehub
import os

# 1. Download garantido via API para evitar corrupção de arquivo
print("Baixando dataset oficial...")
pasta_dataset = kagglehub.dataset_download("mistergomes/microdados-educacao-superior-2020")
nome_arquivo = next(f for f in os.listdir(pasta_dataset) if f.upper() == 'CADASTRO_CURSOS_2020.CSV')
caminho_arquivo = os.path.join(pasta_dataset, nome_arquivo)

# 2. Verificação de integridade (Obrigatório: 335.630 linhas com cabeçalho)
resultado = subprocess.run(['wc', '-l', caminho_arquivo], capture_output=True, text=True)
total_linhas = int(resultado.stdout.split()[0])
if total_linhas != 335630:
    raise ValueError(f"Erro de integridade: Arquivo corrompido com {total_linhas} linhas.")
print("Verificação concluída: Arquivo íntegro com 335.630 linhas.")

# 3. ETL - Limpeza e mapeamento
colunas_interesse = ['TP_REDE', 'QT_ING', 'QT_MAT', 'TP_MODALIDADE_ENSINO']
df_cursos = pd.read_csv(caminho_arquivo, sep=';', encoding='latin1', usecols=colunas_interesse).dropna()

# Binarizando as variáveis para o padrão matemático (0 e 1)
df_cursos['Y_REDE'] = df_cursos['TP_REDE'].map({1: 0, 2: 1})
df_cursos['X3_MODALIDADE'] = df_cursos['TP_MODALIDADE_ENSINO'].map({1: 0, 2: 1})

dataset_final = df_cursos[['QT_ING', 'QT_MAT', 'X3_MODALIDADE', 'Y_REDE']].copy()
print("\nDistribuição das classes:")
print((dataset_final['Y_REDE'].value_counts(normalize=True) * 100).round(2))

"""## 2. Divisão Treino/Teste (Seção 6)
Conforme exigido na Seção 6 do roteiro, **todos** os parâmetros das distribuições e as probabilidades *a priori* devem ser extraídos exclusivamente do conjunto de treinamento. Para evitar vazamento de dados (*data leakage*), fazemos a separação estratificada (70/30) antes de qualquer análise estatística. O nosso desbalanceamento brutal (95% Privada vs 5% Pública) é mantido rigorosamente em ambos os arquivos.
"""

# Separando features e alvo
X = dataset_final[['QT_ING', 'QT_MAT', 'X3_MODALIDADE']]
y = dataset_final['Y_REDE']

# Divisão 70/30 com estratificação para manter a proporção das classes
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.30, random_state=42, stratify=y
)

# Unindo novamente para exportar os CSVs limpos
treino = X_train.join(y_train)
teste = X_test.join(y_test)
treino.to_csv('treino.csv', index=False, sep=';')
teste.to_csv('teste.csv', index=False, sep=';')

print(f"Treinamento: {len(treino)} registros | Teste: {len(teste)} registros")

"""## 3. Hipóteses e Estimação (Etapa 1)
Nesta etapa, tomamos a decisão analítica mais importante do projeto. Inicialmente, cogitamos usar a distribuição Normal para Ingressantes ($X_1$) e Matrículas ($X_2$). No entanto, ao plotarmos os histogramas, notamos que a enorme maioria dos cursos brasileiros é muito pequena (pico próximo a zero), com poucos cursos enormes gerando uma longa cauda à direita. A Normal ficava achatada e projetava densidade para valores negativos.

Para provar isso, criamos um teste formal comparando a Normal com a **Exponencial** via Critério de Informação de Akaike (AIC) e teste de Kolmogorov-Smirnov (KS). A Exponencial venceu com uma ordem de grandeza de vantagem.

Portanto, nossas hipóteses assumidas são:
*   $X_1$ e $X_2$ (Contínuas): **Distribuição Exponencial** ($\lambda = 1 / \mu$).
*   $X_3$ (Categórica binária): **Distribuição de Bernoulli**.
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

df_treino = pd.read_csv('treino.csv', sep=';')
df_publica = df_treino[df_treino['Y_REDE'] == 0]
df_privada = df_treino[df_treino['Y_REDE'] == 1]

# Extração das Probabilidades a Priori P(Y=c)
n_total = len(df_treino)
p_y0 = len(df_publica) / n_total
p_y1 = len(df_privada) / n_total

def verossimilhanca_exponencial(x, lam):
    """Fórmula da densidade Exponencial calculada manualmente: f(x) = lambda * exp(-lambda * x)"""
    return lam * np.exp(-lam * x)

# Extraindo parâmetros de X1 (QT_ING)
lambda_x1_y0 = 1 / df_publica['QT_ING'].mean()
lambda_x1_y1 = 1 / df_privada['QT_ING'].mean()

# Extraindo parâmetros de X2 (QT_MAT)
lambda_x2_y0 = 1 / df_publica['QT_MAT'].mean()
lambda_x2_y1 = 1 / df_privada['QT_MAT'].mean()

# Extraindo parâmetros de X3 (X3_MODALIDADE)
p_x3_y0 = df_publica['X3_MODALIDADE'].mean()
p_x3_y1 = df_privada['X3_MODALIDADE'].mean()

# Impressão completa de todos os parâmetros
print(f"Priors -> P(Y=0): {p_y0:.4f} | P(Y=1): {p_y1:.4f}")
print(f"X1 (Ingressantes) -> Lambda Pública: {lambda_x1_y0:.6f} | Lambda Privada: {lambda_x1_y1:.6f}")
print(f"X2 (Matrículas)   -> Lambda Pública: {lambda_x2_y0:.6f} | Lambda Privada: {lambda_x2_y1:.6f}")
print(f"X3 (Modalidade)   -> P(EaD|Pública): {p_x3_y0:.4f} | P(EaD|Privada): {p_x3_y1:.4f}\n")

# Plotagem visual das Hipóteses de Distribuição (Histograma x Exponencial)
fig, axes = plt.subplots(1, 2, figsize=(12, 4.2))
x1_grid = np.linspace(0, df_treino['QT_ING'].quantile(0.98), 300)
x2_grid = np.linspace(0, df_treino['QT_MAT'].quantile(0.98), 300)

for classe, cor, rotulo, lam1, lam2 in [
    (0, 'tab:blue', 'Pública', lambda_x1_y0, lambda_x2_y0),
    (1, 'tab:orange', 'Privada', lambda_x1_y1, lambda_x2_y1),
]:
    subset = df_treino[df_treino['Y_REDE'] == classe]

    # Gráfico X1
    axes[0].hist(subset['QT_ING'].clip(upper=subset['QT_ING'].quantile(0.98)),
                 bins=40, density=True, alpha=0.4, color=cor, label=f'{rotulo} (dados)')
    axes[0].plot(x1_grid, verossimilhanca_exponencial(x1_grid, lam1), color=cor, linestyle='--',
                 label=f'{rotulo} (Exponencial)')

    # Gráfico X2
    axes[1].hist(subset['QT_MAT'].clip(upper=subset['QT_MAT'].quantile(0.98)),
                 bins=40, density=True, alpha=0.4, color=cor, label=f'{rotulo} (dados)')
    axes[1].plot(x2_grid, verossimilhanca_exponencial(x2_grid, lam2), color=cor, linestyle='--',
                 label=f'{rotulo} (Exponencial)')

axes[0].set_title('X1 (QT_ING): Dados x Exponencial Ajustada')
axes[0].legend(fontsize=8)
axes[1].set_title('X2 (QT_MAT): Dados x Exponencial Ajustada')
axes[1].legend(fontsize=8)
plt.tight_layout()
plt.show()

"""## 4. Análise Univariada de X1 (Ingressantes)
O roteiro nos pede para diferenciar **Verossimilhança** ($p(x|Y=c)$) de **Probabilidade a posteriori** ($P(Y=c|x)$). A verossimilhança nos diz apenas o quão comum é uma observação assumindo que já sabemos a classe (é uma densidade, pode passar de 1). Já a probabilidade a posteriori aplica o Teorema de Bayes para misturar essa evidência com o *prior* do Brasil (95% privada), nos dando a chance real de o curso ser de tal rede (somando 100%).

Como adotamos duas Exponenciais, encontrar a fronteira de decisão (onde as probabilidades se cruzam) exige resolver uma equação estritamente **linear**, não quadrática.
"""

# 1. Razão de Verossimilhanças (Lambda)
def razao_verossimilhanca_exp(x, lam0, lam1):
    return verossimilhanca_exponencial(x, lam1) / verossimilhanca_exponencial(x, lam0)

exemplo_x1 = 100
lam_x1 = razao_verossimilhanca_exp(exemplo_x1, lambda_x1_y0, lambda_x1_y1)
print(f"Para x=100 ingressantes, a Razão Λ(x) é {lam_x1:.4f} (Favorece Y=0, Pública).")

# 2. Teorema de Bayes (Posteriori)
def posterior_exp(x, lam0, p0, lam1, p1):
    l0 = verossimilhanca_exponencial(x, lam0) * p0
    l1 = verossimilhanca_exponencial(x, lam1) * p1
    return l0 / (l0 + l1), l1 / (l0 + l1)

post_0, post_1 = posterior_exp(exemplo_x1, lambda_x1_y0, p_y0, lambda_x1_y1, p_y1)
print(f"Posteriori para x=100 -> P(Y=0|x): {post_0:.4f} | P(Y=1|x): {post_1:.4f}")

# 3. Fronteira de Decisão
def fronteira_decisao_exp(lam0, p0, lam1, p1):
    """Derivação algébrica para igualar os posteriores exponenciais"""
    return (np.log(p1 * lam1) - np.log(p0 * lam0)) / (lam1 - lam0)

front_x1 = fronteira_decisao_exp(lambda_x1_y0, p_y0, lambda_x1_y1, p_y1)
print(f"A fronteira de decisão de X1 ocorre exatamente em: {front_x1:.1f} ingressantes.")

"""## 5. Análise Univariada de X2 (Matrículas)
Aplicamos a mesma lógica algébrica para o total de matrículas. Esperamos que a fronteira seja numericamente maior aqui, já que turmas acumulam alunos de vários semestres.
"""

exemplo_x2 = 400
lam_x2 = razao_verossimilhanca_exp(exemplo_x2, lambda_x2_y0, lambda_x2_y1)
post2_0, post2_1 = posterior_exp(exemplo_x2, lambda_x2_y0, p_y0, lambda_x2_y1, p_y1)

print(f"Para x=400 matrículas, a Razão Λ(x) é {lam_x2:.4f} (Favorece Pública).")
print(f"Posteriori para x=400 -> P(Y=0|x): {post2_0:.4f} | P(Y=1|x): {post2_1:.4f}")

front_x2 = fronteira_decisao_exp(lambda_x2_y0, p_y0, lambda_x2_y1, p_y1)
print(f"A fronteira de decisão de X2 ocorre exatamente em: {front_x2:.1f} matrículas.")

"""## 6. Análise Univariada de X3 (Modalidade)
Sendo categórica (Bernoulli), $X_3$ não possui uma "fronteira contínua", mas sim uma regra lógica por categoria.

Para a comparação qualitativa do **poder de discriminação**, não podemos usar o D de Cohen (que exige normalidade). Para sermos matematicamente rigorosos com nossas distribuições, calculamos o **Coeficiente de Sobreposição (OVL)**. A área não sobreposta (`1 - OVL`) nos dá o ranking de qual variável separa melhor as classes sozinha.
"""

# Regra de decisão da variável categórica
print(f"Probabilidades se Presencial (0): P(Y=0)={1-p_x3_y0:.4f} | P(Y=1)={1-p_x3_y1:.4f}")
print(f"Probabilidades se EaD (1): P(Y=0)={p_x3_y0:.4f} | P(Y=1)={p_x3_y1:.4f}")
print("Regra h3: Se Presencial -> Favorece Pública. Se EaD -> Favorece Privada.")

# Integração numérica para calcular o OVL (Coeficiente de Sobreposição)
def sobreposicao_exponencial(lam0, lam1):
    f0 = lambda x: verossimilhanca_exponencial(x, lam0)
    f1 = lambda x: verossimilhanca_exponencial(x, lam1)
    ovl, _ = quad(lambda x: min(f0(x), f1(x)), 0, np.inf)
    return ovl

ovl_x1 = sobreposicao_exponencial(lambda_x1_y0, lambda_x1_y1)
ovl_x2 = sobreposicao_exponencial(lambda_x2_y0, lambda_x2_y1)

# Para a Bernoulli, a sobreposição é a soma dos mínimos das proporções
ovl_x3 = min(1 - p_x3_y0, 1 - p_x3_y1) + min(p_x3_y0, p_x3_y1)

print("\n--- Ranking de Discriminação (1 - OVL) ---")
print(f"1º X2 (Matrículas): {1 - ovl_x2:.4f}")
print(f"2º X3 (Modalidade): {1 - ovl_x3:.4f}")
print(f"3º X1 (Ingressantes): {1 - ovl_x1:.4f}")

"""## 7. Implementação do Classificador Multivariado
Assumimos aqui a **hipótese de independência condicional**: o classificador calcula a probabilidade matemática assumindo que o número de ingressantes não afeta o número de matrículas.

Para evitar problemas de *underflow* numérico da máquina (multiplicação de probabilidades gerando zeros), implementamos o classificador inteiramente no **domínio logarítmico**. Na função de Bernoulli, aplicamos `np.clip` (Suavização de Laplace) para evitar um erro fatal de `log(0)`.
"""

# Função para a variável categórica com Suavização (Laplace/Epsilon)
def verossimilhanca_bernoulli_suavizada(x, p, eps=1e-6):

    p_suavizado = np.clip(p, eps, 1 - eps)
    # Se x=1 (EaD), retorna p. Se x=0 (Presencial), retorna 1-p.
    return x * p_suavizado + (1 - x) * (1 - p_suavizado)

def prever_naive_bayes_classico(x1, x2, x3):
    # 1. Verossimilhanças isoladas para a classe 0 (Pública)
    lik_x1_0 = verossimilhanca_exponencial(x1, lambda_x1_y0)
    lik_x2_0 = verossimilhanca_exponencial(x2, lambda_x2_y0)
    lik_x3_0 = verossimilhanca_bernoulli_suavizada(x3, p_x3_y0)

    # Teorema de Bayes Clássico (Multiplicação): Priori * p(X1) * p(X2) * p(X3)
    posteriori_0 = p_y0 * lik_x1_0 * lik_x2_0 * lik_x3_0

    # 2. Verossimilhanças isoladas para a classe 1 (Privada)
    lik_x1_1 = verossimilhanca_exponencial(x1, lambda_x1_y1)
    lik_x2_1 = verossimilhanca_exponencial(x2, lambda_x2_y1)
    lik_x3_1 = verossimilhanca_bernoulli_suavizada(x3, p_x3_y1)

    # Teorema de Bayes Clássico (Multiplicação): Priori * p(X1) * p(X2) * p(X3)
    posteriori_1 = p_y1 * lik_x1_1 * lik_x2_1 * lik_x3_1

    # A classe com o maior valor final vence
    return np.where(posteriori_1 > posteriori_0, 1, 0)

"""## 8. Avaliação e Matriz de Confusão
Agora aplicamos a nossa regra de decisão Bayesiana ao arquivo `teste.csv`, que foi isolado e guardado lá no começo.

*   **Verdadeiro Positivo (VP):** Curso privado classificado corretamente como privado.
*   **Verdadeiro Negativo (VN):** Curso público classificado corretamente como público.
*   **Falso Positivo (FP):** Curso público que o modelo se confundiu e rotulou como privado.
*   **Falso Negativo (FN):** Curso privado rotulado incorretamente como público.
"""

df_teste = pd.read_csv('teste.csv', sep=';')

# Realizando as predições com a multiplicação clássica
df_teste['Y_PREDITO'] = prever_naive_bayes_classico(
    df_teste['QT_ING'].values,
    df_teste['QT_MAT'].values,
    df_teste['X3_MODALIDADE'].values
)

cm = confusion_matrix(df_teste['Y_REDE'], df_teste['Y_PREDITO'])
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=['Pública (0)', 'Privada (1)'])

# O parâmetro values_format='d' força a exibição do número real sem notação científica
disp.plot(cmap='Blues', values_format='d')
plt.title('Matriz de Confusão - Naive Bayes (Teste)')
plt.show()

print("\nRelatório de Métricas Oficiais:")
print(classification_report(df_teste['Y_REDE'], df_teste['Y_PREDITO'], target_names=['0 (Pública)', '1 (Privada)']))

"""## 9. Discussão e Limitações Críticas (Item 16)


1.  **A Falsa Premissa de Independência:** O Naive Bayes assume que Ingressantes e Matrículas ocorrem independentemente. Na realidade educacional, elas são fortemente correlacionadas. Tratar essas duas variáveis como independentes significa que nosso modelo está, na prática, contando a mesma "força de evidência" duas vezes.
2.  **O Paradoxo da Acurácia e Desbalanceamento:** O modelo cravou falsos negativos altos. Como o Brasil possui 95% de cursos privados, o modelo cria um viés gigantesco a favor da classe 1. Uma universidade privada populosa cruza nossa fronteira de 120 matrículas rapidamente, enganando o algoritmo e fazendo-o acreditar que é uma federal, justamente porque o classificador precisa de evidências numéricas extremas para ter a "coragem" de contrariar o *prior*.
"""